batch_size: 256
data_code: fashionmnist
n_layers: 5
hidden_width: 128
log_batch_interval: 20
device: cuda
model: linear
atype: relu
learning_rate: 0.001
model_file: hsic_weight_linear_fmnist.pt
epochs_standard: 2
epochs_format: 2
task: 'general'
verbose: 0
ext: pdf
exp_index: null
do_training: True