batch_size: 64
data_code: cifar10
n_layers: 1
hidden_width: 10
log_batch_interval: 2
device: cuda
model: resnet-conv
atype: relu
learning_rate: 0.001
model_file: hsic_weight_resconv_fmnist.pt
epochs_standard: 1
epochs_format: 1
task: general
last_hidden_width: 64
verbose: 1
ext: pdf
exp_index: null
do_training: True