batch_size: 512
learning_rate: 0.001
n_layers: 5
hidden_width: 256
last_hidden_width: 32
epochs_standard: 5
epochs_format: 5
seed: 1234

device: cuda
model: resnet-linear
atype: relu
data_code: mnist
model_file: hsic_weight_reslinear_mnist.pt
task: general
ext: pdf

log_batch_interval: 50
verbose: 0
exp_index: null
do_training: True