batch_size: 512
data_code: mnist
n_layers: 5
hidden_width: 256
log_batch_interval: 50
device: cuda
model: resnet-linear
atype: relu
learning_rate: 0.001
model_file: hsic_weight_reslinear_mnist.pt
epochs_standard: 5
epochs_format: 5
task: general
last_hidden_width: 32
verbose: 0
ext: pdf