batch_size: 256
learning_rate: 0.001
n_layers: 1
hidden_width: 3
last_hidden_width: 64
log_batch_interval: 2
epochs_standard: 1
epochs_format: 1

device: cuda
model: resnet-conv
atype: relu
data_code: mnist
model_file: hsic_weight_resconv_mnist.pt
task: general
ext: pdf

verbose: 0
exp_index: null
do_training: True