batch_size: 32
data_code: cifar10
n_layers: 5
hidden_width: 10
log_batch_interval: 2
device: cuda
model: resnet-conv
atype: relu
learning_rate: 0.001
model_file: hsic_weight_resconv_cifar10-0060.pt
epochs_standard: 5
epochs_format: 5
task: general
last_hidden_width: 128
verbose: 0
ext: pdf
exp_index: null
do_training: True