batch_size: 256
data_code: mnist
n_layers: 5
hidden_width: 128
log_batch_interval: 2
device: cuda
model: linear
atype: relu
learning_rate: 0.001
model_file: hsic_weight_linear_mnist.pt
epochs: 5
task: general
verbose: 0
ext: pdf
exp_index: null
do_training: True
