batch_size: 512
data_code: 'cifar10'
n_layers: 5
hidden_width: 10
log_batch_interval: 50
device: 'cuda'
model: 'resnet-conv'
learning_rate: 0.001
model_file: hsic_weight_resconv.pt
epochs_standard: 10
epochs_format: 10
task: 'general'
last_hidden_width: 64
verbose: 0