batch_size: 64
data_code: 'mnist'
n_layers: 5
hidden_width: 8
log_batch_interval: 50
device: 'cuda'
model: 'conv'
learning_rate: 0.001
model_file: hsic_weight_conv.pt
epochs_standard: 5
epochs_format: 5
task: 'general'
last_hidden_width: 32
verbose: 0