batch_size: 256
data_code: mnist
n_layers: 5
hidden_width: 10
log_batch_interval: 2
device: cuda
model: resnet-conv
atype: relu
learning_rate: 0.001
model_file: hsic_weight_resconv_mnist.pt
epochs_standard: 5
epochs_format: 5
task: general
last_hidden_width: 64
verbose: 0
ext: pdf