batch_size: 256
learning_rate: 0.001
n_layers: 5
hidden_width: 8
last_hidden_width: 32 # it is for last dense layer
epochs_standard: 2
epochs_format: 2
seed: 1234

device: cuda
model: conv
atype: relu
data_code: mnist
model_file: hsic_weight_conv_mnist.pt
task: general
ext: pdf

log_batch_interval: 50
verbose: 0
exp_index: null
do_training: True