batch_size: 512
data_code: mnist
n_layers: 5
hidden_width: 10
log_batch_interval: 20
device: cuda
model: resnet-conv
atype: relu
hsic_learning_rate: 0.0005
sigma_hx: 40.
sigma_hy: 40.
lambda_x: 1.
lambda_y: 250.
model_file: hsic_weight_resconv_mnist.pt
checkpoint: null
epochs_hsic: 30
task: hsic-train
last_hidden_width: 128
verbose: 1
exp_index: null
do_training: True