batch_size: 256
hsic_learning_rate: 0.0001
n_layers: 5
hidden_width: 256
last_hidden_width: 32
log_batch_interval: 20
device: cpu
model: resnet-linear
atype: relu

sigma_hx: 30.
sigma_hy: 30.
lambda_x: 1.
lambda_y: 200.

data_code: mnist
model_file: hsic_weight_reslinear_mnist.pt
checkpoint: null
epochs_hsic: 10
task: hsic-train

verbose: 0
exp_index: null
do_training: True