batch_size: 256
learning_rate: 0.001
n_layers: 5
hidden_width: 128
sigma_hx: 30.
sigma_hy: 30.
lambda_x: 1
lambda_y: 200.
epochs: 5

device: cuda
model: linear
data_code: mnist
checkpoint: null
task: hsic-solve
ext: pdf
training_type: backprop # backprop/format 

log_batch_interval: 25
verbose: 0
exp_index: null
do_training: True
