batch_size: 256
data_code: fashionmnist
n_layers: 5
hidden_width: 128
log_batch_interval: 25
device: cuda
model: linear
learning_rate: 0.0001
hsic_learning_rate: 0.0001
sigma_hx: 30.
sigma_hy: 30.
lambda_x: 1
lambda_y: 200.
epochs_standard: 5
epochs_hsic: 5
task: hsic-solve
verbose: 0
ext: pdf
exp_index: null
do_training: False