batch_size: 128
data_code: 'cifar10'
n_layers: 5
hidden_width: 10
log_batch_interval: 20
device: 'cuda'
model: 'resnet-conv'
hsic_learning_rate: 0.0001
sigma_hx: 30.
sigma_hy: 30.
lambda_x: 1.
lambda_y: 200.
model_file: hsic_weight_resconv.pt
epochs_hsic: 10
task: 'hsic-train'
last_hidden_width: 64
verbose: 1
