batch_size: 512
data_code: cifar10
n_layers: 5
hidden_width: 20
log_batch_interval: 20
device: cuda
model: resnet-conv
atype: relu
hsic_learning_rate: 0.0005
sigma_hx: 50.
sigma_hy: 10.
lambda_x: 1.
lambda_y: 500.
model_file: hsic_weight_resconv_cifar10.pt
checkpoint: null
epochs_hsic: 300
task: hsic-train
last_hidden_width: 256
verbose: 1
exp_index: null
do_training: True