batch_size: 512
data_code: cifar10
n_layers: 5
hidden_width: 10
log_batch_interval: 20
device: cuda
model: resnet-conv
atype: relu
hsic_learning_rate: 0.0002
sigma_hx: 30.
sigma_hy: 30.
lambda_x: 1.
lambda_y: 250.
model_file: hsic_weight_resconv_cifar10.pt
checkpoint: null
epochs_hsic: 60
task: hsic-train
last_hidden_width: 128
verbose: 1
exp_index: null
do_training: True