batch_size: 512
learning_rate: 0.0001
sigma_hx: 1.
sigma_hy: 1.
lambda_x: 1
lambda_y: 200
epochs: 5
last_hidden_width: 10
seed: 1234

data_code: mnist
model: needle
log_batch_interval: 20
device: cuda
ext: pdf
task: needle
training_type: backprop # hsictrain/backprop two options

checkpoint: null
verbose: 1
exp_index: null
do_training: True
