batch_size: 512
data_code: mnist
model: needle
log_batch_interval: 50
device: cuda
learning_rate: 0.0001
hsic_learning_rate: 0.0001
sigma_hx: 25.
sigma_hy: 25.
lambda_x: 1
lambda_y: 300
epochs_standard: 5
epochs_hsic: 5 
checkpoint: null
last_hidden_width: 10
task: needle
verbose: 0
ext: pdf
exp_index: null
do_training: True
