batch_size: 512
learning_rate: 0.0001
sigma_hx: 25.
sigma_hy: 25.
lambda_x: 1
lambda_y: 300
epochs: 5
last_hidden_width: 10

data_code: mnist
model: needle
log_batch_interval: 50
device: cuda
ext: pdf
task: needle
training_type: backprop # hsictrain/backprop two options

checkpoint: null
verbose: 0
exp_index: null
do_training: True
