batch_size: 512
data_code: mnist
model: niddle
log_batch_interval: 50
device: cuda
learning_rate: 0.0002
hsic_learning_rate: 0.0002
sigma_hx: 40.
sigma_hy: 40.
lambda_x: 1.
lambda_y: 200.
epochs_standard: 5
epochs_hsic: 10
last_hidden_width: 10
task: niddle
verbose: 0
ext: pdf