batch_size: 256
data_code: 'mnist'
model: 'niddle'
log_batch_interval: 50
device: 'cuda'
learning_rate: 0.0001
hsic_learning_rate: 0.0001
sigma_hx: 30.
sigma_hy: 30.
lambda_x: 1.
lambda_y: 200.
epochs_standard: 5
epochs_hsic: 5
task: 'niddle'
verbose: 0