batch_size: 256 # for hsic-training, task.task_variedep determines format-trainin batchsize
learning_rate: 0.0001
sigma_hx: 30.
sigma_hy: 30.
lambda_x: 1.
lambda_y: 200.
epochs: 5
n_layers: 5
hidden_width: null # determined by task.task_varieddim
last_hidden_width: null

device: cuda
model: linear
atype: relu
data_code: mnist
model_file: hsic_weight_varied_dim_mnist.pt # will be modified by task.task_varieddim
checkpoint: null
training_type: hsictrain # script
task: varied-dim

verbose: 0
log_batch_interval: 20
exp_index: null # determined by task.task_varieddim

