batch_size: 256
hidden_width: 64
learning_rate: 0.0005
sigma_hx: 15.
sigma_hy: 15.
epochs: 5
last_hidden_width: 64
n_layers: null # determined by script/task_varieddepth.sh


device: cuda
model: linear
atype: relu
task: varied-depth
data_code: mnist
training_type: backprop
ext: pdf

verbose: 0
log_batch_interval: 20
exp_index: null # determined by task.task_varieddepth
do_training: True
