batch_size: 128
data_code: mnist
n_layers: 5
hidden_width: 64
log_batch_interval: 20
device: cuda
model: linear
atype: null # determined by engine.core.dispatcher
learning_rate: 0.0005
sigma_hx: 15.
sigma_hy: 15.
epochs_standard: 5
task: varied-activation
last_hidden_width: 64
verbose: 0
ext: pdf
