batch_size: 256 # for hsic-training, task.task_variedep determines format-trainin batchsize
learning_rate: 0.0001
sigma_hx: 30.
sigma_hy: 30.
lambda_x: 1.
lambda_y: 200.
epochs: null # determined by script
n_layers: 5
hidden_width: 128
last_hidden_width: 32
seed: 1234

device: cuda
model: linear
atype: relu
data_code: mnist
model_file: hsic_weight_varied_epoch_mnist.pt # will be modified by task.task_variedep
checkpoint: null
training_type:
task: varied-epoch

verbose: 0
log_batch_interval: 20
exp_index: null # determined by task.task_variedep
