TTYPE_STANDARD = 'standard'
TTYPE_HSICTRAIN = 'hsictrain'
TTYPE_FORMAT = 'format'


FONTSIZE_TITLE  = 32
FONTSIZE_XLABEL = 30
FONTSIZE_YLABEL = 30
FONTSIZE_XTICKS = 22
FONTSIZE_YTICKS = 22
FONTSIZE_LEDEND = 28