TTYPE_STANDARD = 'standard'
TTYPE_HSICTRAIN = 'hsictrain'
TTYPE_FORMAT = 'format'


FONTSIZE_TITLE  = 36
FONTSIZE_XLABEL = 34
FONTSIZE_YLABEL = 34
FONTSIZE_XTICKS = 22
FONTSIZE_YTICKS = 22
FONTSIZE_LEDEND = 28
